root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides:
  - files: "./packages/backend/jest-resolver.js"
    rules:
      "@typescript-eslint/no-var-requires": "off"
  - files: "*.spec.ts"
    rules:
      "@typescript-eslint/no-non-null-assertion": "off"
  - files: "*.d.ts"
    rules:
      no-var: "off"
