plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@shelf/jest-mongodb@<=2.2.0":
    dependencies:
      jest-environment-node: "^27.5.1"

enableScripts: false
