// Generated by Trezor with passphrase "robiniscool"

export const legacyAccountBTC = {
  extendedKey:
    "xpub6Cw9YG38NXy6zQGPziJo7pLrzemwdyyMYVAaHZRXwcmfjsfRaQJmbyxkxzL1pE1u3898bKriUkaTK6GtRPCnryZjGZoAi8HPkDr6ns63nus",
  publicKeys: [
    "0367359c51b41e7e3f5648161b063c7a6d8c8bc25482c337106469e9d6d75e908f",
  ],
  addresses: ["195nYLPg9NTdCzTeZT9Db5txc1FRAJC7UH"],
};
