version: "3.9"
services:
  db:
    container_name: mongo
    image: mongo:5.0.6
    volumes:
      - invoice-data:/data/db
      - ./mongodb/seed:/docker-entrypoint-initdb.d/
      - ./mongodb/workaround:/home/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_DATABASE_ADMIN_USERNAME
      - MONGO_INITDB_DATABASE_ADMIN_PASSWORD
volumes:
  invoice-data:
