name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: "yarn all:format:check"
      - run: "yarn backend:lint"
      - run: "yarn backend:test"
